### ISSUE TITLE
cannot create userdata at /data/gsi/dsu

### ISSUE THREAD

**Issue by u0-ani-nya** [VegaBobo/DSU-Sideloader#116]
emm this appear no matter i use root/shizuku/system（by magisk）
I also tried change this foder to 777 and belongs to everybody
this didn’t helps

env： oneplus 8 In2010 （CN ver） with oxygenos13 swapped
log：

Device: IN2013
SDK: Android 13 (33)
UserSelection(userSelectedUserdata=21474836480, userSelectedImageSize=-1, selectedFileUri=content://com.android.externalstorage.documents/document/primary%3Adsu%2FMikuUI-TDA-0.18.0-arm64-ab-gapps-20230717-UNOFFICIAL%2Fsystem.img, selectedFileName=system.img)
SingleSystemImage(uri=content://com.android.externalstorage.documents/tree/primary%3Adsu/document/primary%3Adsu%2Fworkspace_dsuhelper%2Fsystem.img.gz, fileSize=4230184960, type=SINGLE_SYSTEM_IMAGE)
InstallationPreferences(isUnmountSdCard=true, useBuiltinInstaller=false)
operationMode: SHIZUKU
Package: vegabobo.dsusideloader
Version: 2.03 - 8 (release})
checkDynamicPartitions: true
checkUnavaiableStorage: true
checkReadLogsPermission: true
allocPercentage: 0.4
hasAvailableStorage: true
maximumAllowedForAllocation: 35

--------- beginning of main
D/DynamicSystemInstallationService: onStartCommand(): action=android.os.image.action.START_INSTALL
--------- beginning of system
I/DynamicSystemService: startInstallation -> /data/gsi/dsu
D/DynamicSystemInstallationService: status: IN_PROGRESS, cause: CAUSE_NOT_SPECIFIED, partition name: userdata, progress: 0/21474836480, total_progress: 0%
E/gsid    : Failed to create file at: /data/gsi/dsu/userdata_gsi.img: Permission denied
E/gsid    : Could not determine maximum file size for /data/gsi/dsu/userdata_gsi.img
E/gsid    : Could not create userdata image
I/DynamicSystemService: Failed to create partition: userdata
E/gsid    : [liblp]std::unique_ptr<LpMetadata> android::fs_mgr::ReadFromImageFile(const std::string &) open failed: /metadata/gsi/dsu/dsu/lp_metadata: No such file or directory
E/gsid    : Could not read metadata file /metadata/gsi/dsu/dsu/lp_metadata
E/gsid    : Installation failed, clean up: userdata_gsi
E/gsid    : Installation failed: install_dir=/data/gsi/dsu/, dsu_slot=dsu, partition_name=userdata
D/DynamicSystemInstallationService: status: NOT_STARTED, cause: ERROR_IO, detail: java.io.IOException: Failed to start installation with requested size: 21474836480

**Comment by VegaBobo** [comment]
Try enabling full logcat logging (go to about section, tap in the application icon a lot of times), after doing so, go back, and select "Full logcat logging", and try installing again, installation should fail, but it should give us more log information, get new logs and send them here, maybe it gives us something we can analyze further

**Comment by 3bdelrhman-rabie** [comment]
> Try enabling full logcat logging (go to about section, tap in the application icon a lot of times), after doing so, go back, and select "Full logcat logging", and try installing again, installation should fail, but it should give us more log information, get new logs and send them here, maybe it gives us something we can analyze further

Device: M2101K6G
SDK: Android 11 (30)
UserSelection(userSelectedUserdata=26843545600, userSelectedImageSize=-1, selectedFileUri=content://com.android.externalstorage.documents/document/primary%3ADownload%2FGsi%2FPixelExperience_Plus_arm64-ab-13.0-20230821-UNOFFICIAL.img.xz, selectedFileName=PixelExperience_Plus_arm64-ab-13.0-20230821-UNOFFICIAL.img.xz)
SingleSystemImage(uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FGsi/document/primary%3ADownload%2FGsi%2Fworkspace_dsuhelper%2FPixelExperience_Plus_arm64-ab-13.0-20230821-UNOFFICIAL.img.gz, fileSize=3532144640, type=SINGLE_SYSTEM_IMAGE)
InstallationPreferences(isUnmountSdCard=false, useBuiltinInstaller=false)
operationMode: ROOT
Package: vegabobo.dsusideloader
Version: 2.03 - 8 (release})
checkDynamicPartitions: true
checkUnavaiableStorage: true
checkReadLogsPermission: true
allocPercentage: 0.4
hasAvailableStorage: true
maximumAllowedForAllocation: 41

--------- beginning of system
08-23 17:22:49.147  1055  6340 I ActivityManager: Force stopping com.android.dynsystem appid=1000 user=0: from pid 14769
08-23 17:22:49.148  1055  6340 I ActivityManager: Killing 5897:com.android.dynsystem:dynsystem/1000 (adj 925): stop com.android.dynsystem due to from pid 14769
--------- beginning of main
08-23 17:22:49.155 14735 14775 D DsuInstallationHandler: Starting DSU VerificationActivity: Intent { act=android.os.image.action.START_INSTALL dat=content://com.android.externalstorage.documents/tree/primary:Download/Gsi/document/primary:Download/Gsi/workspace_dsuhelper/PixelExperience_Plus_arm64-ab-13.0-20230821-UNOFFICIAL.img.gz flg=0x10000000 cmp=com.android.dynsystem/.VerificationActivity (has extras) }
08-23 17:22:49.157  1055  5311 I ActivityTaskManager: START u0 {act=android.os.image.action.START_INSTALL dat=content://com.android.externalstorage.documents/tree/primary:Download/Gsi/document/primary:Download/Gsi/workspace_dsuhelper/PixelExperience_Plus_arm64-ab-13.0-20230821-UNOFFICIAL.img.gz flg=0x10000000 cmp=com.android.dynsystem/.VerificationActivity (has extras)} from uid 0
08-23 17:22:49.159  3096  3096 D RegisteredNfcFServicesCache: Service unchanged, not updating
08-23 17:22:49.161 12160 12160 D CarrierSvcBindHelper: No carrier app for: 0
08-23 17:22:49.162 12160 12160 E PhoneInterfaceManager: [PhoneIntfMgr] getCarrierPackageNamesForIntentAndPhone: No UICC
08-23 17:22:49.162 12160 12160 D CarrierSvcBindHelper: No carrier app for: 1
08-23 17:22:49.178  1055  1103 D CompatibilityChangeReporter: Compat change id reported: 135634846; UID 1000; state: DISABLED
08-23 17:22:49.178  1055  1103 D CompatibilityChangeReporter: Compat change id reported: 135754954; UID 1000; state: ENABLED
08-23 17:22:49.180  9759  9759 E USAP    : Attempt to invoke virtual method 'int com.android.internal.os.ZygoteCommandBuffer.getCount()' on a null object reference
08-23 17:22:49.181  1055  1126 E ZygoteProcess: IO Exception while communicating with USAP pool - Connection reset by peer
08-23 17:22:49.184  2110  2110 V ShadeControllerImpl: NotificationShadeWindow: com.android.systemui.statusbar.phone.NotificationShadeWindowView{3ed8087 I.E...... ......ID 0,0-1080,2400} canPanelBeCollapsed(): false
08-23 17:22:49.195   739   739 D Zygote  : Forked child process 15458
08-23 17:22:49.195   739   739 I Zygote  : Process 5897 exited due to signal 9 (Killed)
08-23 17:22:49.196  1055  1126 I ActivityManager: Start proc 15458:com.android.dynsystem:dynsystem/1000 for pre-top-activity {com.android.dynsystem/com.android.dynsystem.VerificationActivity}
08-23 17:22:49.209 15458 15458 E ystem:dynsyste: Not starting debugger since process cannot load the jdwp agent.
08-23 17:22:49.221  1055  1127 I libprocessgroup: Successfully killed process cgroup uid 1000 pid 5897 in 72ms
08-23 17:22:49.255 15458 15458 I ystem:dynsyste: The ClassLoaderContext is a special shared library.
08-23 17:22:49.263 15458 15458 D NetworkSecurityConfig: No Network Security Config specified, using platform default
08-23 17:22:49.263 15458 15458 D NetworkSecurityConfig: No Network Security Config specified, using platform default
08-23 17:22:49.267   626   646 W DisplayIdentification: Invalid EDID: falling back to serial number due to missing display name.
08-23 17:22:49.267   626   646 W DisplayIdentification: Invalid EDID: falling back to ASCII text due to missing serial number.
08-23 17:22:49.273 15458 15458 D VerificationActivity: This device is not protected by a password/pin
08-23 17:22:49.273 15458 15458 D VerificationActivity: Starting Installation Service
08-23 17:22:49.286 15458 15458 D DynSystemInstallationService: onStartCommand(): action=android.os.image.action.START_INSTALL
08-23 17:22:49.288 15458 15482 D InstallationAsyncTask: Start doInBackground(), URL: content://com.android.externalstorage.documents/tree/primary%3ADownload%2FGsi/document/primary%3ADownload%2FGsi%2Fworkspace_dsuhelper%2FPixelExperience_Plus_arm64-ab-13.0-20230821-UNOFFICIAL.img.gz
08-23 17:22:49.290  1055  5311 D CompatibilityChangeReporter: Compat change id reported: 136219221; UID 1000; state: ENABLED
08-23 17:22:49.310 15458 15482 D KeyRevocationList: Fetch from URL: https://dl.google.com/developers/android/gsi/gsi-keyblacklist.json
08-23 17:22:49.500  1055  1055 W NotificationHistory: Attempted to add notif for locked/gone/disabled user 0
08-23 17:22:49.637 15458 15482 D KeyRevocationList: Begin of revocation list
08-23 17:22:49.638 15458 15482 D KeyRevocationList: End of revocation list
08-23 17:22:49.640  1055  6340 I DynamicSystemService: startInstallation -> /data/gsi/dsu
08-23 17:22:49.646 15458 15482 D InstallationAsyncTask: Creating partition: userdata
08-23 17:22:49.652  5924  5924 E gsid    : Extent at location 0 of file /data/gsi/dsu/userdata_gsi.img has unsupported flags
08-23 17:22:49.652  5924  5924 E gsid    : Failed to read fiemap of file: /data/gsi/dsu/userdata_gsi.img
08-23 17:22:49.653  5924  5924 E gsid    : Could not determine maximum file size for /data/gsi/dsu/userdata_gsi.img
08-23 17:22:49.653  5924  5924 E gsid    : Could not create userdata image
08-23 17:22:49.653  5924  5924 E gsid    : [liblp]std::unique_ptr<LpMetadata> android::fs_mgr::ReadFromImageFile(const std::string &) open failed: /metadata/gsi/dsu/dsu/lp_metadata: No such file or directory
08-23 17:22:49.653  5924  5924 E gsid    : Could not read metadata file /metadata/gsi/dsu/dsu/lp_metadata
08-23 17:22:49.654  1055  6340 I DynamicSystemService: Failed to install userdata
08-23 17:22:49.659 15458 15482 E InstallationAsyncTask: java.io.IOException: Failed to start installation with requested size: 26843545600
08-23 17:22:49.659 15458 15482 E InstallationAsyncTask: java.io.IOException: Failed to start installation with requested size: 26843545600
08-23 17:22:49.659 15458 15482 E InstallationAsyncTask: 	at com.android.dynsystem.InstallationAsyncTask.installUserdata(InstallationAsyncTask.java:334)
08-23 17:22:49.659 15458 15482 E InstallationAsyncTask: 	at com.android.dynsystem.InstallationAsyncTask.doInBackground(InstallationAsyncTask.java:186)
08-23 17:22:49.659 15458 15482 E InstallationAsyncTask: 	at com.android.dynsystem.InstallationAsyncTask.doInBackground(InstallationAsyncTask.java:46)
08-23 17:22:49.659 15458 15482 E InstallationAsyncTask: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
08-23 17:22:49.659 15458 15482 E InstallationAsyncTask: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08-23 17:22:49.659 15458 15482 E InstallationAsyncTask: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
08-23 17:22:49.659 15458 15482 E InstallationAsyncTask: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-23 17:22:49.659 15458 15482 E InstallationAsyncTask: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-23 17:22:49.659 15458 15482 E InstallationAsyncTask: 	at java.lang.Thread.run(Thread.java:923)
08-23 17:22:49.664 15458 15458 D InstallationAsyncTask: onPostExecute(), URL: content://com.android.externalstorage.documents/tree/primary%3ADownload%2FGsi/document/primary%3ADownload%2FGsi%2Fworkspace_dsuhelper%2FPixelExperience_Plus_arm64-ab-13.0-20230821-UNOFFICIAL.img.gz, result: 3
08-23 17:22:49.664 15458 15458 D DynSystemInstallationService: status=NOT_STARTED, cause=ERROR_IO, detail=java.io.IOException: Failed to start installation with requested size: 26843545600

**Comment by 3bdelrhman-rabie** [comment]
> 

This fixed my problem :

Typed in termux as root : 

setprop persist.sys.fflag.override.settings_dynamic_system 1

and 


pm enable com.android.documentsui

**Comment by Progoodgood1** [comment]
> > 
> 
> This fixed my problem :
> 
> Typed in termux as root :
> 
> setprop persist.sys.fflag.override.settings_dynamic_system 1
> 
> and
> 
> pm enable com.android.documentsui

Any no root way?

**Comment by Mali81shoosh** [comment]
Same issue 
Attached full logs as I couldn't paste here as it is very long 

[logs.txt](https://github.com/user-attachments/files/19823383/logs.txt)

**Comment by ayusc** [comment]
> > 
> 
> This fixed my problem :
> 
> Typed in termux as root :
> 
> setprop persist.sys.fflag.override.settings_dynamic_system 1
> 
> and
> 
> pm enable com.android.documentsui

pm enable com.android.documentsui                      <

Exception occurred while executing 'enable':
java.lang.IllegalArgumentException: Unknown package: com.android.documentsui
        at com.android.server

there is no such package
