### ISSUE TITLE
dsu sideloader setup fails

### ISSUE THREAD

**Issue by theteeth** [VegaBobo/DSU-Sideloader#179]
I get an "has no registered input channel" error in MATLOG libre. So I don't get to enter or create a folder. Android 10 arm64
Any advice
Thanks

**Comment by theteeth** [comment]
hi again. now got full error log below. Maybe there is an adb command to allocate the folder in setup to get around the problem?
FATAL EXCEPTION: main
Process: vegabobo.dsusideloader, PID: 16485
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2058)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1716)
	at android.app.Activity.startActivityForResult(Activity.java:5334)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:2)
	at androidx.core.app.ActivityCompat$Api16Impl.startActivityForResult(ActivityCompat.java:1)
	at androidx.activity.ComponentActivity$2.onLaunch(ComponentActivity.java:274)
	at androidx.activity.result.ActivityResultRegistry$3.launch(ActivityResultRegistry.java:32)
	at androidx.activity.compose.ActivityResultLauncherHolder.launch(ActivityResultRegistry.kt:5)
	at androidx.activity.compose.ManagedActivityResultLauncher.launch(ActivityResultRegistry.kt:3)
	at vegabobo.dsusideloader.ui.cards.warnings.SetupStorageKt$SetupStorage$1$1$1.invoke(SetupStorage.kt:5)
	at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$2.invoke(Clickable.kt:17)
	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1$1.invokeSuspend(TapGestureDetector.kt:128)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:8)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:78)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:129)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:44)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:17)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.dispatchPointerEvent(SuspendingPointerInputFilter.kt:56)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:9)
	at androidx.compose.ui.node.BackwardsCompatNode.onPointerEvent-H0pRuoY(BackwardsCompatNode.kt:14)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:96)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:78)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:78)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:78)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:78)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:78)
	at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:54)
	at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(PointerInputEventProcessor.kt:158)
	at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(AndroidComposeView.android.kt:78)
	at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(AndroidComposeView.android.kt:231)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(AndroidComposeView.android.kt:90)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3113)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2777)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3113)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2777)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3113)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2777)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3113)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2777)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:465)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1849)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4135)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:423)
	at android.view.View.dispatchPointerEvent(View.java:13734)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5661)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5455)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4954)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5007)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4973)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5113)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4981)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5170)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4954)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5007)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4973)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4981)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4954)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7761)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7730)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7681)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7900)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:188)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:336)
	at android.os.Looper.loop(Looper.java:174)
	at android.app.ActivityThread.main(ActivityThread.java:7437)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@26a04e3, androidx.compose.runtime.BroadcastFrameClock@f336ee0, StandaloneCoroutine{Cancelling}@5eea599, AndroidUiDispatcher@a67505e]
